local RTC_TOCNAME,RTC = ...

-- Basic localizations
function RTC.GetLocale()
	local ColRed="|cffff4040"
	
	local DefaultEnGB = {
			["MsgNbRolls"] = "%d Roll(s)",
			["MsgRollCleared"] = "All rolls have been cleared.",
			["MsgUndoRoll"]="Undo all rolls.",
			["MsgAnnounce"] = "%s won with a roll of %d.",
			["MsgAnnounceTie"] = "Tie, %s won with a roll of %d.",
			["MsgNotRolled"]="The following people still need to roll or say '%s'",
			["MsgCheat"]="Ignoring %s's roll of %s (%s-%s).",  -- (player, roll, max_roll, min_roll)
			["MsgStart"]="New roll starting now! Type '/rnd' or '%s'",
			["MsgStartGreenAndNeed"]="New roll starting now! Type '/rnd' for need, '/rnd 1-50' for greed or '%s'",
			["MsgNextItem"]="Next item: %s",
			["MsgTooltip"]="|cffff4040Left click|r to open RTC |n|cffff4040Shift+Left click|r to open 'Loot Rolls'|n|cffff4040Right click|r to open options",
			["MsgBar"]="==============================",
			["MsgLocalRestart"]="The setting is not transferred until after a restart (/reload)",
			["MsgNbLoots"]="%d stored loot(s).",
			["MsgLootLine"]="%s: %s receives loot: %s", -- date, name, item
			["MsgLootCleared"] = "All stored loots have been cleared.",
			["MsgUndoLoot"]="Undo all loots.",
			["MsgLTnotenabled"]="Loot Tracker is not enabled.",
			["MsgRaidRoll"] = "%s won. (%d)",
			["MsgForcedAnnounce"]="No rolls",
			["MsgStartCD"]="Start a countdown with right click on [Announce] or '/rtc cd'",
						
			["TxtGreed"]="Greed",
			["TxtNeed"]="Need",
			["TxtLine"]="------------------------------------------------------------------------------------------------------",
			["pass"] = "pass",		
			
			["BtnClear"]="Clear",
			["BtnUndo"]="Undo",
			["BtnNotRolled"]="Not rolled",
			["BtnRoll"]="Roll",
			["BtnAnnounce"]="Announce",
			["BtnGreed"]="Greed",
			["BtnPass"]="Pass",			
			["BtnOpen"]="Open",
			["BtnConfig"]="Settings",
			["BtnLootRolls"]="Loot Rolls",
			["BtnOpenLoot"]="Loot Tracker",
			["BtnCSVExport"]="CSV Export",
			["BtnCancel"]="Cancel",
			["BtnRaidRoll"]="Raid Roll",
			["BtnColorNormal"]="Colour text",
			["BtnColorCheat"]="Colour cheat",
			["BtnColorGuild"]="Colour guild",
			["BtnColorInfo"]="Colour info",		
			["BtnColorChat"]="Colour chat message",
			["BtnColorScroll"]="Colour list entry",
			
			["EdtWhiteList"]="Whitelist ItemIds",
			["EdtNbLoots"]="Maximum stored loot",
			["EdtCSVexport"]="CSV-Export-Format",
			["EdtCDRefresh"]="Refresh Countdown after roll (seconds)",
			["EdtDefaultCD"]="Default Countdown (seconds)",	
			["EdtAutoCloseDelay"]="Delayed closing in seconds",
			["EdtAnnounceList"]="Entries in the announcement list",
			
			["TxtCSVJokers"]="%% %name% %class% %timestamp% %dd% %mm% %yy% %HH% %MM% %SS%",
			["TxtCSVJokers2"]="%iname% %irarity% %iraritytxt% %ilevel% %iid% %iprice% %icount% %itype% %itypetxt%",
			["TxtCSVJokersTitle"]="For CSV-Export you can use this jokers:",
			["TxtItemType"]="Attention! ItemType is independent of the rarity!",
			
			["TabRoll"]="Rolls",
			["TabLoot"]="Loot",
			["TabCSV"]="CSV",
			
			["PanelLootTracker"]="Loot Tracker",
			["HeaderRarity"]="Track Rarity",
			["HeaderItemType"]="Track ItemType",
			["HeaderSettings"]="Settings",
			["HeaderCustomLocales"]="Localization",
			["HeaderCSV"]="CSV-Export",
			["PanelAbout"]="About",
			["HeaderSlashCommand"]="Slash Commands",
			["HeaderCredits"]="Credits",
			["HeaderInfo"]="Information",
			["HeaderUsage"]="Usage",
		
			["Cboxshowminimapbutton"]="Show minimap button",
			["CboxLockMinimapButton"]="Lock minimap button position",		
			["CboxLockMinimapButtonDistance"]="Minimize minimap button distance",
			["CboxCloseOnClear"]="Close window after [Clear]",
			["CboxClearOnAnnounce"]="Clear rolls after [Announce]",
			["CboxCloseOnAnnounce"]="Close window after [Announce]",
			["CboxClearOnClose"]="Clear rolls after [Close]",
			["CboxIgnoreDouble"]="Ignore double rolls",
			["CboxRejectOutBounds"]="Reject rolls with bounds other than (1-100)",
			["CboxAnnounceIgnoreDouble"]="Only with [Announce]: Ignore double rolls",
			["CboxAnnounceRejectOutBounds"]="Only with [Announce]: Reject rolls with bounds other than (1-100)",
			["CboxNeedAndGreed"]="Use Need '/rnd' and Greed '/rnd 1-50' system, ignores out of bounce",
			["CboxShowNotRolled"]="Show [Not rolled] button",
			["CboxAutoLootRolls"]="Open 'Loot Rolls' automatically",
			["CboxAutoCloseLootRolls"]="Automatic close 'Loot Rolls' when everyone has rolled",
			["CboxClearOnStart"]="Clear when somebody starts a new roll",
			["CboxOpenOnStart"]="Open when somebody starts a new roll",
			["CboxColorName"]="Colorize names by class",
			["CboxShowClassIcon"]="Show class icon",
			["CboxOnDebug"]="Show debug information",
			["CboxShowGuildRank"]="Show guild rank",
			["CboxAutmaticAnnounce"]="Automatic announce rolls",
			
			["CboxNotfiyInnone"]="Enable on overworld",
			["CboxNotfiyInpvp"]="Enable in battleground",
			["CboxNotfiyInparty"]="Enable in dungeon",
			["CboxNotfiyInraid"]="Enable in raid dungeon",
			
			
			["CboxLTShortMessage"]="Short Message",
			["CboxLTTrackSolo"]="Track solo",
			["CboxLTTrackGroup"]="Track party",
			["CboxLTTrackSRaid"]="Track raid with 10 or less members",
			["CboxLTTrackBRaid"]="Track raid with 11 or more members",
			["CboxLTEnable"]="Enable loot tracking",
			["CboxLTSmallFont"]="Small font",
			["CboxLTShowIcon"]="Show item icon",
			
			["SlashClearRolls"]="Clear rolls",
			["SlashClearLoot"]="Clear loot",
			["SlashClearLootRolls"]="Clear 'Loot Rolls'",
			["SlashUndoRolls"]="Recover last rolls",
			["SlashUndoLoot"]="Recover last loots",
			["SlashAnnounce"]="Announce winner of the last roll",
			["SlashNotRolled"]="Remind everyone who has not rolled",
			["SlashClose"]="Close main window",
			["SlashReset"]="Reset position of main window",
			["SlashConfig"]="Open Configuration",
			["SlashAbout"]="Open about",
			["SlashStart"]="Announce a new roll, <value> can be empty or itemlink",
			["SlashOpen"]="Open main window",
			["SlashRaidRoll"]="Roll a player name",
			["SlashRaidRollList"]="Output all player",
			["SlashCountdown"]="Countdown <value> in seconds",
			
			["AboutInfo"]="Have you ever tried to roll the 'Onyxia Hide Backpack' in a raid? RTC collects all roll results and sorts them. Ever thought about whether you wanted something for your second-equip, but didn't know if somebody needed it? RTC can automatically open the Blizzard 'Loot rolls' window, where you can see immediately who needs or has greed.|nIn raid ever lost the overview, who got what? Again, RTC can help you. On request, it records all items, including a variable export function.",
			
			["AboutSlashCommand"]="<value> can be true, 1, enable, false, 0, disable. If <value> is omitted, the current status switches.",
			
			["AboutUsage"]="RTC will automatically open when someone rolls the dice. Double rolls or rolls outside the default range are ignored on request.|nBy default, the automatic opening of 'Loot Rolls' is disabled. Likewise, the 'Loot Tracker' must be turned on manually.",
			
			

			
		}
		
	local locales = {
		deDE = {
			["AboutInfo"] = "Hast du jemals versucht, um den 'Rucksack aus Onyxias Haut' in Raid zu verwürfeln? RTC sammelt alle Würfelergebnisse und sortiert sie. Schon mal überlegt, ob du was für dein Zweit-Equip haben wolltest, aber nicht wusstest, ob wer bedarf hat? RTC kann dir automatisch das Blizzard 'Beuteverteilung' Window öffnen. Dort siehst du sofort wer bedarf oder gier hat.|nIn Raid jemals die Übersicht verloren, wer was bekommen hat? Auch hier kann RTC dir helfen. Auf Wunsch zeichnet es alle Gegenstände auf, inklusive einer variablen Export-Funktion.",
			["AboutSlashCommand"] = "<value> kann true,1,enable,false,0,disable sein. Wird <value> weggelassen, schaltet der aktuelle Status um.",
			["AboutUsage"] = "RTC wird sich automatisch öffnen, wenn jemand würfelt. Doppelte Würfel oder würfe außerhalb des Standard-Bereichs werden auf wunsch ignoriert.|nStandardmäßig ist das automatische öffnen von 'Beuteverteilung' deaktivert. Genauso muss der 'Loot Tracker' manuell eingeschaltet werden.",
			["BtnAnnounce"] = "Ansagen",
			["BtnCancel"] = "Abbruch",
			["BtnClear"] = "Löschen",
			["BtnColorChat"] = "Chat-Nachricht-Farbe",
			["BtnColorCheat"] = "Cheat-Farbe",
			["BtnColorGuild"] = "Gilden-Farbe",
			["BtnColorInfo"] = "Info-Farbe",
			["BtnColorNormal"] = "Text-Farbe",
			["BtnColorScroll"] = "Listeneintrag-Farbe",
			["BtnConfig"] = "Einstellungen",
			["BtnCSVExport"] = "CSV Export",
			["BtnGreed"] = "Gier",
			["BtnLootRolls"] = "Beuteverteilung",
			["BtnNotRolled"] = "Fehlende",
			["BtnOpen"] = "Öffnen",
			["BtnOpenLoot"] = "Loot Tracker",
			["BtnPass"] = "Passen",
			["BtnRaidRoll"] = "Raid Roll",
			["BtnRoll"] = "Würfeln",
			["BtnUndo"] = "Undo",
			["CboxAnnounceIgnoreDouble"] = "Nur bei [Ansagen]: Doppelte Würfe ignorieren",
			["CboxAnnounceRejectOutBounds"] = "Nur bei [Ansagen]: Würfe außerhalb 1-100 ignorieren",
			["CboxAutmaticAnnounce"] = "Würfelergebnisse automatisch ansagen",
			["CboxAutoCloseLootRolls"] = "'Beuteverteilung' automatisch schließen, wenn verwürfelt",
			["CboxAutoLootRolls"] = "'Beuteverteilung' automatisch öffnen",
			["CboxClearOnAnnounce"] = "Würfelergebnisse löschen nach [Ansagen]",
			["CboxClearOnClose"] = "Würfelergebnisse löschen nach [Schließen]",
			["CboxClearOnStart"] = "Würfelergebnisse löschen, wenn jemand eine neue Würfelrunde startet",
			["CboxCloseOnAnnounce"] = "Fenster schließen nach [Ansagen]",
			["CboxCloseOnClear"] = "Fenster schließen nach [Löschen]",
			["CboxColorName"] = "Namen nach Klasse einfärben",
			["CboxIgnoreDouble"] = "Doppelte Würfe ignorieren",
			["CboxLockMinimapButton"] = "Minimap-Icon-Position sperren",
			["CboxLockMinimapButtonDistance"] = "Minimap-Icon-Entfernung minimieren",
			["CboxLTEnable"] = "Aktiviere loot tracking",
			["CboxLTShortMessage"] = "Kurzformat",
			["CboxLTShowIcon"] = "Zeige Beute-Icon",
			["CboxLTSmallFont"] = "Kleine Schrift",
			["CboxLTTrackBRaid"] = "Nur im Raud mít 11 oder mehr",
			["CboxLTTrackGroup"] = "Nur in einer Gruppe",
			["CboxLTTrackSolo"] = "Nur wenn alleine",
			["CboxLTTrackSRaid"] = "Nur im Raid mit 10 oder weniger",
			["CboxNeedAndGreed"] = "Verwende das Bedarf '/rnd' und Gier '/rnd 1-50' System, Würfe außerhalb ignorieren",
			["CboxNotfiyInnone"] = "Auf der Welt aktiv",
			["CboxNotfiyInparty"] = "In Instanz aktiv",
			["CboxNotfiyInpvp"] = "In Schlachtfeldern aktiv",
			["CboxNotfiyInraid"] = "In Schlachtzugs-Instanzen aktiv",
			["CboxOnDebug"] = "Zeige Debug-Informationen",
			["CboxOpenOnStart"] = "RTC öffnen, wenn jemand eine neue Würfelrunde startet",
			["CboxRejectOutBounds"] = "Würfe außerhalb 1-100 ignorieren",
			["CboxShowClassIcon"] = "Klassenzeichen anzeigen",
			["CboxShowGuildRank"] = "Zeige Gildenränge",
			["Cboxshowminimapbutton"] = "Minimap-Icon anzeigen",
			["CboxShowNotRolled"] = "Zeige [Fehlende] Button",
			["EdtAnnounceList"] = "Einträge in der Ansagen-Liste",
			["EdtAutoCloseDelay"] = "Verzögertes schließen in Sekunden",
			["EdtCDRefresh"] = "Countdown nach einem Wurf (Sekunden)",
			["EdtCSVexport"] = "CSV-Export-Format",
			["EdtDefaultCD"] = "Standard Countdown (Sekunden)",
			["EdtNbLoots"] = "Maximale Anzahl der gespeicherten Beute",
			["EdtWhiteList"] = "Whitelist ItemIds",
			["HeaderCredits"] = "Credits",
			["HeaderCSV"] = "CSV-Export",
			["HeaderCustomLocales"] = "Lokalisierung",
			["HeaderInfo"] = "Information",
			["HeaderItemType"] = "Beachte ItemType",
			["HeaderRarity"] = "Beachte Seltenheit",
			["HeaderSettings"] = "Einstellungen",
			["HeaderSlashCommand"] = "Befehle",
			["HeaderUsage"] = "Usage",
			["MsgAnnounce"] = "%s hat mit einer %d gewonnen",
			["MsgAnnounceTie"] = "Gleichstand, %s haben mit einer %d gewonnen.",
			["MsgBar"] = "==============================",
			["MsgCheat"] = "%s wurf mit %s (%s-%s) wird ignoriert.",
			["MsgForcedAnnounce"] = "Keine Würfelergebnisse",
			["MsgLocalRestart"] = "Die Lokalisierung wird erst nach einem Neustart übernommen (/reload)",
			["MsgLootCleared"] = "Sämtliche gespeichte Beute gelöscht",
			["MsgLootLine"] = "%s: %s erhält Beute: %s",
			["MsgLTnotenabled"] = "Loot Tracker ist nicht aktiv",
			["MsgNbLoots"] = "%d gespeicherte Beute.",
			["MsgNbRolls"] = "%d Würfelergebnisse",
			["MsgNextItem"] = "Nächster Gegenstand: %s",
			["MsgNotRolled"] = "Noch nicht gewürfelt oder '%s' geschrieben:",
			["MsgRaidRoll"] = "RaidRoll: %s hat gewonnen (%d)",
			["MsgRollCleared"] = "Alle Würfelergebnisse gelöscht.",
			["MsgStart"] = "Neue Würfelrunde! Gib '/rnd' oder '%s' ein",
			["MsgStartCD"] = "Den Countdown mit rechtsklick auf [Ansagen] oder '/rtc cd' starten",
			["MsgStartGreenAndNeed"] = "Neue Würfelrunde! Gib '/rnd' für Bedarf, '/rnd 1-50' für Gier oder '%s' ein",
			["MsgTooltip"] = "|cffff4040Linksklick|r für RTC|n|cffff4040Shift+Linksklick|r für 'Beuteverteilung'|n|cffff4040Rechtsklick|r für Einstellungen",
			["MsgUndoLoot"] = "Beute wiederhergestellt.",
			["MsgUndoRoll"] = "Alle Würfelergebnisse wieder hergestellt.",
			["PanelAbout"] = "Über",
			["PanelLootTracker"] = "Loot Tracker",
			["pass"] = "passe",
			["SlashAbout"] = "About öffnen",
			["SlashAnnounce"] = "Gewinner der letzten Würfelrunde bekannt geben",
			["SlashClearLoot"] = "Beute löschen",
			["SlashClearLootRolls"] = "'Beuteverteilung' löschen",
			["SlashClearRolls"] = "Würfelergebnisse löschen",
			["SlashClose"] = "Hauptfenster schließen",
			["SlashConfig"] = "Konfiguration öffnen",
			["SlashCountdown"] = "Countdown <value> in Sekunden",
			["SlashNotRolled"] = "Jeden erinnern, noch zu würfeln",
			["SlashOpen"] = "Hauptfenster öffnen",
			["SlashRaidRoll"] = "Würfle einen Mitspielernamen",
			["SlashRaidRollList"] = "Ausgabe aller Mitspieler",
			["SlashReset"] = "Fensterposition zurücksetzen",
			["SlashStart"] = "Neue Würfelrunde ankündigen, <value> kann leer oder ein ItemLink sein",
			["SlashUndoLoot"] = "Letzte Beute wiederherstellen",
			["SlashUndoRolls"] = "Letzte Würfelergebnisse wiederherstellen",
			["TabCSV"] = "CSV",
			["TabLoot"] = "Beute",
			["TabRoll"] = "Würfe",
			["TxtCSVJokers"] = "%% %name% %class% %timestamp% %dd% %mm% %yy% %HH% %MM% %SS%",
			["TxtCSVJokers2"] = "%iname% %irarity% %iraritytxt% %ilevel% %iid% %iprice% %icount% %itype% %itypetxt%",
			["TxtCSVJokersTitle"] = "Für den CSV-Export stehen folgende Joker zur Verfügung",
			["TxtGreed"] = "Gier",
			["TxtItemType"] = "Achtung! ItemType ist unabhängig von der Seltenheit!",
			["TxtLine"] = "------------------------------------------------------------------------------------------------------",
			["TxtNeed"] = "Bedarf"
		},
		esMX = {
			["MsgRollCleared"] = "Todas las tiradas han sido borradas.",
			["MsgNbRolls"] = "%d Tiradas",
		},
		frFR = {
			["MsgRollCleared"] = "Tous les jets ont été effacés.",
			["MsgNbRolls"] = "%d Jet(s)",
		},
		ruRU =  {
			["AboutInfo"] = "Вы когда-нибудь пытались разыграть «Рюкзак из шкуры Ониксии» в рейде? RTC собирает все результаты бросков и сортирует их. Когда-нибудь задумывались о том, хотите ли вы что-нибудь для своего второго снаряжения, но не знаете, нужно ли это кому-нибудь? RTC может автоматически открывать окно Blizzard 'Розыгрыша добычи', где вы можете сразу увидеть, кому нужно, а кто не откажется.|nIn В рейде когда-либо теряли обзор, кто что получил? Опять же, RTC может помочь вам. По запросу записываются все предметы, включая функцию экспорта переменных.",
			["AboutSlashCommand"] = "<значение> может быть верным, 1, включить, ложным, 0, отключить. Если <значение> опущено, текущий статус переключиться.",
			["AboutUsage"] = "RTC автоматически открывается, когда кто-то бросает кости. Двойные броски или броски вне диапазона по умолчанию игнорируются по запросу.|nПо умолчанию автоматическое открытие 'Розыгрыш добычи' отключено. Аналогично, 'Розыгрыш добычи' должен быть включен вручную.",
			["BtnAnnounce"] = "Объявить",
			["BtnCancel"] = "Отмена",
			["BtnClear"] = "Очистить",
			["BtnColorChat"] = "Цветное сообщение чата",
			["BtnColorCheat"] = "Цвет мошенничества",
			["BtnColorGuild"] = "Цвет гильдии",
			["BtnColorInfo"] = "Информация о цвете",
			["BtnColorNormal"] = "Цвет текста",
			["BtnColorScroll"] = "Цвет записи в списке",
			["BtnConfig"] = "Настройки",
			["BtnCSVExport"] = "CSV Экспорт",
			["BtnGreed"] = "Не откажусь",
			["BtnLootRolls"] = "Розыгрыш предметов",
			["BtnNotRolled"] = "Не разыграно",
			["BtnOpen"] = "Открыть",
			["BtnOpenLoot"] = "Отслеживание добычи",
			["BtnPass"] = "Пас",
			["BtnRaidRoll"] = "Рейдовый бросок",
			["BtnRoll"] = "Разыграть",
			["BtnUndo"] = "Вернуть",
			["CboxAnnounceIgnoreDouble"] = "Только после [Объявить]: Игнорировать двойные броски",
			["CboxAnnounceRejectOutBounds"] = "Только после [Объявить]: Отклонить розыгрыш с диапазоном не (1-100)",
			["CboxAutmaticAnnounce"] = "Автоматическое объявление розыгрыша",
			["CboxAutoCloseLootRolls"] = "Автоматически закрывать 'Розыгрыш предметов' когда все разыграли",
			["CboxAutoLootRolls"] = "Открывать 'Розыгрыш предметов' автоматически",
			["CboxClearOnAnnounce"] = "Очистить броски после [Объявления]",
			["CboxClearOnClose"] = "Очистить броски после [Закрыть]",
			["CboxClearOnStart"] = "Очищено, когда кто-то начинает новый розыгрыш",
			["CboxCloseOnAnnounce"] = "Закрыть окно после [Объявления]",
			["CboxCloseOnClear"] = "Закрыть окно после [Очистки]",
			["CboxColorName"] = "Раскрасить имена по классам",
			["CboxIgnoreDouble"] = "Игнорировать двойные броски",
			["CboxLockMinimapButton"] = "Блокировка положения кнопки у миникарты",
			["CboxLockMinimapButtonDistance"] = "Минимизировать расстояние до миникарты",
			["CboxLTEnable"] = "Включить отслеживание добычи",
			["CboxLTShortMessage"] = "Короткое сообщение",
			["CboxLTShowIcon"] = "Показать значок предмета",
			["CboxLTSmallFont"] = "Маленький шрифт",
			["CboxLTTrackBRaid"] = "Отслеживание рейда с 11 или более участниками",
			["CboxLTTrackGroup"] = "Отследить группу",
			["CboxLTTrackSolo"] = "Отслеживать в одиночку",
			["CboxLTTrackSRaid"] = "Отслеживание рейдов с 10 или менее участниками",
			["CboxNeedAndGreed"] = "'Не откажусь' - '/rnd' и 'Не откажусь' - '/rnd 1-50' , игнор ошибок",
			["CboxNotfiyInnone"] = "Включить в мире",
			["CboxNotfiyInparty"] = "Включить в подземелье",
			["CboxNotfiyInpvp"] = "Включить на полях битвы",
			["CboxNotfiyInraid"] = "Включить в рейдовом подземелье",
			["CboxOnDebug"] = "Показать отладочную информацию",
			["CboxOpenOnStart"] = "Открыть, когда кто-то начинает новый бросок",
			["CboxRejectOutBounds"] = "Отклонить броски с диапазоном не (1-100)",
			["CboxShowClassIcon"] = "Показать значок класса",
			["CboxShowGuildRank"] = "Показать звание гильдии",
			["Cboxshowminimapbutton"] = "Показать кнопку у миникарты",
			["CboxShowNotRolled"] = "Показать [Пас] кнопку",
			["EdtAnnounceList"] = "Записи в списке объявлений",
			["EdtAutoCloseDelay"] = "Задержка закрытия в секундах",
			["EdtCDRefresh"] = "Обновить отсчет после броска (в секундах)",
			["EdtCSVexport"] = "CSV-Экспорт-Формат",
			["EdtDefaultCD"] = "Обратный отсчет по умолчанию (в секундах)",
			["EdtNbLoots"] = "Максимально сортируемая добыча",
			["EdtWhiteList"] = "Белый список ItemIds",
			["HeaderCredits"] = "Авторы",
			["HeaderCSV"] = "CSV-Экспорт",
			["HeaderCustomLocales"] = "Перевод",
			["HeaderInfo"] = "Информация",
			["HeaderItemType"] = "Отслеживать по типу предмета",
			["HeaderRarity"] = "Отслеживать по редкости",
			["HeaderSettings"] = "Настройки",
			["HeaderSlashCommand"] = "/ Команды",
			["HeaderUsage"] = "Использование",
			["MsgAnnounce"] = "%s выигрывает с броском %d.",
			["MsgAnnounceTie"] = "Ничья, %s выигрывает с броском %d.",
			["MsgBar"] = "==============================",
			["MsgCheat"] = "Игнорировать %s бросок от %s (%s-%s).",
			["MsgForcedAnnounce"] = "Нет бросков",
			["MsgLocalRestart"] = "Настройка не передается до перезагрузки (/reload)",
			["MsgLootCleared"] = "Все хранимые добычи были очищены.",
			["MsgLootLine"] = "%s: %s получает добычу: %s",
			["MsgLTnotenabled"] = "Отслеживание добычи не включено.",
			["MsgNbLoots"] = "%d хранимая добыча(и).",
			["MsgNbRolls"] = "%d бросок(и)",
			["MsgNextItem"] = "Новый бросок: %s",
			["MsgNotRolled"] = "Эти люди еще не роллили или не сказали '%s'",
			["MsgRaidRoll"] = "%s выиграл. (%d)",
			["MsgRollCleared"] = "Все броски очищены.",
			["MsgStart"] = "Новый розыгрыш стартовал! Напиши '/rnd' или '%s'",
			["MsgStartCD"] = "Начните обратный отсчет правой кнопкой мыши на [Объявить] или '/rtc cd'",
			["MsgStartGreenAndNeed"] = "Новый розыгрыш стартовал! Напиши '/rnd' если 'Нужно', '/rnd 1-50' для не откажусь или '%s'",
			["MsgTooltip"] = "|cffff4040ЛКМ|r для открытия RTC |n|cffff4040Нажмите ШИФТ+ЛКМ|r открыть 'Розыгрыш предметов'|n|cffff4040ПКМ|r открыть настройки",
			["MsgUndoLoot"] = "Отменить все лоты.",
			["MsgUndoRoll"] = "Отменить все броски",
			["PanelAbout"] = "Информация",
			["PanelLootTracker"] = "Отслеживание добычи",
			["pass"] = "пас",
			["SlashAbout"] = "Информация",
			["SlashAnnounce"] = "Объявить победителя последнего розыгрыша",
			["SlashClearLoot"] = "Убрать добычу",
			["SlashClearLootRolls"] = "Очистить 'Розыгрыш добычи'",
			["SlashClearRolls"] = "Очистить броски",
			["SlashClose"] = "Закрыть главное окно",
			["SlashConfig"] = "Открыть конфигурацию",
			["SlashCountdown"] = "Обратный отсчет <значение> в секундах",
			["SlashNotRolled"] = "Напомните всем, кто еще не бросал",
			["SlashOpen"] = "Открыть главное окно",
			["SlashRaidRoll"] = "Имя бросавшего игрока",
			["SlashRaidRollList"] = "Вывести всех игроков",
			["SlashReset"] = "Сбросить положение главного окна",
			["SlashStart"] = "Объявить новый розыгрыш, <значение> может быть пустым или ссылка на предмет",
			["SlashUndoLoot"] = "Восстановить последнею добычу",
			["SlashUndoRolls"] = "Восстановить последние броски",
			["TabCSV"] = "CSV",
			["TabLoot"] = "Добыча",
			["TabRoll"] = "Броски",
			["TxtCSVJokers"] = "%% %name% %class% %timestamp% %dd% %mm% %yy% %HH% %MM% %SS%",
			["TxtCSVJokers2"] = "%iname% %irarity% %iraritytxt% %ilevel% %iid% %iprice% %icount% %itype% %itypetxt%",
			["TxtCSVJokersTitle"] = "Для CSV-Экспорта вы можете использовать следующие джокеры:",
			["TxtGreed"] = "Не откажусь",
			["TxtItemType"] = "Внимание! Тип добычи не зависит от редкости!",
			["TxtLine"] = "------------------------------------------------------------------------------------------------------",
			["TxtNeed"] = "Мне это нужно"
		},
		zhCN = {
			["MsgRollCleared"] = "所有骰子已被清除。",
			["MsgNbRolls"] = "%d个骰子",
		},
		zhTW = {
			["MsgRollCleared"] = "所有擲骰紀錄已被清除。",
			["MsgNbRolls"] = "共計 %d 人擲骰",
		},
	}
	

	
	
	
	
	
	locales.esES=locales.esMX
	
	if RollTrackerClassicDB and RollTrackerClassicDB.OnDebug then
		for lkey,loc in pairs(locales) do
			if loc["MsgStart"] then
				for key,value in pairs(DefaultEnGB) do
					if loc[key]==nil then --or loc[key]==value then
						print ("RTC-Missing:"..lkey.."["..key.."]")
					end
				end
			end	
		end
	end
	
	
	local L = locales[GetLocale()] or {}
	
	if RollTrackerClassicDB and RollTrackerClassicDB.CustomLocales and type(RollTrackerClassicDB.CustomLocales) == "table" then
		for key,value in pairs(RollTrackerClassicDB.CustomLocales) do
			if value~=nil and value ~="" then
				L[key.."_org"]=L[key]
				L[key]=value
			end
		end
	end
	
	setmetatable(DefaultEnGB,{__index =function(t,k) return "["..k.."]" end})
	
	setmetatable(L, {
		__index = DefaultEnGB
	})
	L["AboutCredits"]="Russian translation by Arrogant_Dreamer, tierggg and Hubbotu|nBaudzilla for the idea of the resize-code|nRollTracker Classic is an updated version of 'RollTracker Lite', originally by Jerry Chong - zanglang@gmail.com."
	
	
	return L
end