local L = LibStub("AceLocale-3.0"):NewLocale("MyChatAlert", "esMX")
if not L then return end

--[[
    MyChatAlert localization done through curseforge
    https://www.curseforge.com/wow/addons/mychatalert/localization
    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]--


