-- scope stuff
karmarang = karmarang or {};
karmarang.localizations = karmarang.localizations or {};
karmarang.localizations["deDE"] = karmarang.localizations["deDE"] or {};

-- keys
local L = karmarang.localizations["deDE"];
L["AddOn loaded. Type /karma for options."] 										                = "AddOn geladen. Tippe /karma für Optionen.";
L["Database validation complete."]                                                                  = "Datenbank-Validierung abgeschlossen.";
L["Error while validating database. In order for Karmarang to work properly, it needed to be reset. We are sorry. :("] = "Fehler während der Datenbank-Validierung. Damit Karmarang weiterhin funktioniert, musste die Datenbank zurückgesetzt werden. Es tut uns leid. :(";
L["Module loaded."] 											                                    = "Modul geladen.";
L["yes"] 																			                = "ja";
L["no"] 																			                = "nein";
L["Unknown command. Possible parameters are: /karma ..."] 							                = "Unbekannter Befehl. Mögliche Parameter sind: /karma ...";
L["Apply"] 																			                = "Annehmen";
L["Cancel"] 																		                = "Abbrechen";
L["Reset"] 																		                    = "Zurücksetzen";
L["This will reset the Karmarang database.\n\nAre you sure?"]                                       = "Dies wird die Karmarang-Datenbank zurücksetzen.\n\nSind Sie sicher?";
L["Database has been reset successfully."]                                                          = "Datenbank erfolgreich zurückgesetzt.";
L["... and %s further results."]                                                                    = "... und %s weitere Ergebnisse.";
L["cache -> Toggles database caching on startup."]                                                  = "cache -> Schaltet Datenbank-Caching beim Start ein oder aus.";
L["get [text] -> Searches the database for player names containing [text]."]                        = "get [text] -> Sucht in der Datenbank nach Spielernamen, die [text] enthalten.";
L["pref -> Toggles whether your own comments are preferred for tooltips or not."]                   = "pref -> Schaltet um, ob deine eigenen Kommentare in den Tooltips priorisiert werden oder nicht.";
L["reset -> Resets the Karmarang database."]                                                        = "reset -> Setzt die Karmarang-Datenbank zurück.";
L["Karma"]                                                                                          = "Karma";
L["You are about to\n|cff00ff00UPVOTE|r\nthe player \"%s\"."]                                       = "Du bist dabei, den Spieler \"%s\" zu\n|cff00ff00UPVOTEN|r.";
L["You are about to\n|cffff0000DOWNVOTE|r\nthe player \"%s\"."]                                     = "Du bist dabei, den Spieler \"%s\" zu\n|cffff0000DOWNVOTEN|r.";
L["You are about to rate the player \"%s\" neutrally."]                                             = "Du bist dabei, den Spieler \"%s\" neutral zu bewerten.";
L["unknown"]                                                                                        = "unbekannt";
L["notify -> Toggles whether or not you will be notified about received Karma broadcasts or not."]  = "notify -> Schaltet um, ob du über eingehende Karma broadcasts benachrichtigt wirst oder nicht.";
L["comm -> Toggles Karma broadcasts (automatically joins the Karma_Broadcast channel if active)."]  = "comm -> Schaltet um, ob du an Karma broadcasts teilnimmst (tritt automatisch dem Karma_Broadcast-Channel bei wenn aktiv).";
L["Participating in Karma broadcasts: "]                                                            = "Teilnahme an Karma broadcasts: ";
L["Notifications about incoming Karmas: "]                                                          = "Benachrichtigungen über empfangene Karmas: ";
L["Your own comments are preferred for tooltips."]                                                  = "Eigene Kommentare werden für Tooltips bevorzugt.";
L["Your own comments are NOT preferred for tooltips."]                                              = "Eigene Kommentare werden NICHT für Tooltips bevorzugt.";
L["No players found for: \"%s\"."]                                                                  = "Keine Spieler gefunden für: \"%s\".";
L["Broadcast channel joined. You are participating in Karma broadcasts."]                           = "Broadcast-Channel beigetreten. Du nimmst an Karma broadcasts teil.";
L["Attention: You are not participating in Karma broadcasts. Type \"/karma comm\" to enable Karma broadcasts."] = "Achtung: Du nimmst nicht an Karma broadcasts teil. Tippe \"/karma comm\", um Karma broadcasts zu aktivieren.";
L["Broadcast channel left. You are no longer participating in Karma broadcasts."]                   = "Broadcast-Channel verlassen. Du nimmst nicht länger an Karma broadcasts teil.";
L["Warning: Joining Karma broadcast channel failed."]                                               = "Warnung: Beitritt des Karma broadcast channels fehlgeschlagen.";
L["\"%s\" already received Karma today!"]                                                           = "\"%s\" hat heute schon Karma erhalten!"
L["|cff00ff00Upvote and comment|r"]                                                                 = "|cff00ff00Upvoten und kommentieren|r";
L["Neutral (comment only)"]                                                                         = "Neutral (nur Kommentar)";
L["|cffff0000Downvote and comment|r"]                                                               = "|cffff0000Downvoten und kommentieren|r";
L["\n\n Comment (optional):"]                                                                       = "\n\n Kommentar (optional):"
L["Received Karma broadcast from \"%s\"."]                                                          = "Karma broadcast von \"%s\" empfangen.";
L["Your Karma: "]                                                                                   = "Dein Karma: ";